### PR TITLE
Qmk 0.19.1

### PR DESCRIPTION
**Pull request by 13r0ck**
Rebase onto qmk 0.19.1, will need to be force pushed once approved.

Requires https://github.com/pop-os/keyboard-configurator/pull/156

### CODE REVIEW

**Comment by ids1024** [comment]
Since upstream seemed happy to accept `launch_1` (https://github.com/qmk/qmk_firmware/pull/15395), we should see about submitting lite/heavy/other changes upstream too. That will benefit users who wish to compile upstream QMK from source, and make rebases like this easier as well.

**Comment by leviport** [comment]
So far, so good on my launch_1. I'll do some testing on launch_lite_1 today, and we'll need to do some testing on launch_2 and launch_heavy_1 as well.

**Review by leviport — APPROVED** [review]
- launch_1:
  - [x] DFU programming
  - [x] SPI programming
  - [x] Changing LEDs in configurator
  - [x] Changing keymap in configurator

- launch_lite_1: 
  - [x] DFU programming
  - [x] SPI programming
  - [x] Changing LEDs in configurator
  - [x] Changing keymap in configurator

- launch_2:
  - [x] DFU programming
  - [x] SPI programming
  - [x] Changing LEDs in configurator
  - [x] Changing keymap in configurator

- launch_heavy_1:
  - [x] DFU programming
  - [x] SPI programming
  - [x] Changing LEDs in configurator
  - [x] Changing keymap in configurator

**Comment by 13r0ck** [comment]
still waiting on https://github.com/pop-os/keyboard-configurator/pull/156

**Review by jackpot51 — APPROVED** [review]

**Comment by jackpot51** [comment]
@13r0ck why does this require https://github.com/pop-os/keyboard-configurator/pull/156? Shouldn't it be that the keyboard-configurator PR requires this instead?

**Comment by 13r0ck** [comment]
For production. If we push new firmware its going to break their workflow

**Review by jackpot51 — CHANGES_REQUESTED** [review]
@13r0ck does not want this merged yet

**Comment by 13r0ck** [comment]
I am going to start working on this again. Superseded by #34 as there is no reason to stay on this old version.

**Pull request closed without merging**
