### PR TITLE
Launch 3

### PR DESCRIPTION
**Pull request by jackpot51**
Adds launch_3 board which is using the RP2040 controller

### CODE REVIEW

**Comment by leviport** [comment]
Is this ready for reviews? I have a launch_3.1 PCB in a Heavy, and I've been using it for a few days without any issues.

**Comment by jackpot51** [comment]
I am ready if you are ready @leviport

**Comment by leviport** [comment]
Oh one more thing; should this be tested with supporting keyboard-configurator changes, or can that be handled after getting this firmware tested and merged?

**Comment by leviport** [comment]
Looks like "UNLOCKED" mode isn't working on this version. It seems to put it into bootloader mode instead, but I'm not sure it's flashing quite right when flashing with the make commands in this bootloader mode. Seems like I need to flash it twice for it to actually change the keymap to the one I specify in the make command.

Plugging in while holding Esc flashes the correct keymap and seems to reset the keyboard, but keypresses don't work until I unplug and re-plug after flashing.

**Comment by leviport** [comment]
The LED mapping correction is looking good, but I'm still seeing the weirdness I mentioned above with "UNLOCKED" mode.

While testing https://github.com/pop-os/keyboard-configurator/pull/181, I discovered that it could change LEDs on launch_{heavy_}3, but my changes are lost when I unplug/replug the keyboard. I'm not sure if that's an issue with that PR or with this firmware, so I also wanted to mention it here: https://github.com/pop-os/keyboard-configurator/pull/181#issuecomment-1662931038

**Comment by ids1024** [comment]
One thing I see is that `launch_heavy_3` defines `EEPROM_SIZE` as `1024`, like `launch_1` and `launch_2`, but unlike `launch_heavy_1`, which is using `2048`. Probably should be `2048`? But not relevant to an issue that also applies to `launch_3`.

I don't think anything in the Configurator should cause that, if it works normally with other keyboards. I don't know how the EEPROM on this controller compares.

**Comment by leviport** [comment]
The launch_heavy_3 I've been using for several days seems to have just keeled over. I've tested it on multiple computers with multiple USB cables, and it doesn't show any signs of life or show up in `lsusb`. I'll dig into it tomorrow to see if I can learn anything more specific about what happened.

**Comment by jackpot51** [comment]
If you can give this a try again, that would help. The updated QMK from the thelio-io branch may improve things. Also, please try the other launch boards.

**Comment by g-berthiaume** [comment]
I think merging this PR would solve #45

**Comment by leviport** [comment]
UNLOCKED mode no longer puts the controller into bootloader mode, and it no longer takes more than one flash to see the keymap change. 

The last remaining oddity I'm seeing is that after flashing with `make` and putting the controller into bootloader mode, the board resets and the LEDs come back on, but the keyboard is unresponsive until I unplug the keyboard and plug it back in. I'm not sure whether we want to consider this blocking or not.

I'll begin regression testing on other Launch models now.

**Comment by leviport** [comment]
Received a 3.2 prototype. So far the only problem I'm seeing is that LED settings that I set in the Configurator are dumped and reset to the default LED mode every time the keyboard is unplugged and plugged back in. Changes to the keymap itself seem to stick around just fine though.

**Pull request merged**
